version: "2"

services:
  odoo:
    container_name: odoo
    image: odoo:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # DB parameters 
      - HOST=db
      - USER=odoo
      - PASSWORD=${PSQL_PASSWORD}
    networks: 
      # Backend Local Network
      - odoo-db
      # Frontend Local Network
      - odoo-web
    volumes:
      # addons here
      # config file
      - ./odoo:/etc/odoo
      # log file
      - ./logs/odoo:/var/log/odoo/
      # filestore:
      - odoo-web-data:/var/lib/odoo

  db:
    container_name: odoo_db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks: 
      # Backend Local Network
      - odoo-db  
    volumes:
      # psql filestore
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      # psql log file
      - ./logs/postgresql:/var/log/postgresql

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on: 
      - odoo
    ports:
      # HTTP port
      - 80:80
    networks: 
      # Frontend Local Network
      - odoo-web  
    volumes:
      # nginx log file
      - ./logs/nginx:/var/log/nginx
      # nginx config file
      - ./nginx:/etc/nginx/conf.d
      # certificates files
      - ./ssl/certbot/letsencrypt:/etc/letsencrypt
      # website config files
      - ./ssl/certbot/www/html:/var/www/html  

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot -w /var/www/html --rsa-key-size 4096 --noninteractive --email admin@asasatas.com.sa --agree-tos --no-eff-email -d ${CLIENT_WEBSITE}
    depends_on: 
      - nginx
    volumes:
      # certificates files
      - ./ssl/certbot/letsencrypt:/etc/letsencrypt
      # website config files
      - ./ssl/certbot/www/html:/var/www/html
      # certbot log file
      - ./logs/letsencrypt:/var/log/letsencrypt

  nginx-ssl:
    container_name: nginx-ssl 
    image: nginx:latest 
    restart: unless-stopped
    depends_on: 
      - odoo
    ports:
      # HTTP port
      - 80:80
      # HTTPS port
      - 443:443
    networks: 
      # Frontend Local Network
      - odoo-web  
    volumes:
      # nginx log file
      - ./logs/nginx:/var/log/nginx
      # certificates files
      - ./ssl/certbot/letsencrypt:/etc/letsencrypt
      # website config files
      - ./ssl/certbot/www/html:/var/www/html    
      # nginx config file
      - ./ssl/nginx:/etc/nginx/conf.d
      # To generate DH params for more security, run the dhparams-gen script 
      - ./ssl/letsencrypt:/etc/conf/letsencrypt

  certbot-ssl:
    container_name: certbot-ssl 
    image: certbot/certbot:latest 
    command: renew --no-random-sleep-on-renew
    depends_on: 
      - nginx-ssl
    volumes:
      # certificates files
      - ./ssl/certbot/letsencrypt:/etc/letsencrypt
      # website config files
      - ./ssl/certbot/www/html:/var/www/html
      # certbot log file
      - ./logs/letsencrypt:/var/log/letsencrypt


networks:
  odoo-db:
  odoo-web:   


volumes:
  odoo-web-data:
  odoo-db-data:
